version: "3.9"

services: 
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - local.env
    ports: 
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

