version: "3.9"

services:
  mongo:
    container_name: mongo
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - mongo.env
    volumes:
      - mongo_data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - mongo.env

volumes:
  mongo_data: